---
- name: install tomcat server
  hosts: tomcatNode
  become: true

  tasks:
  - name: install java
    yum:
      name: java
      state: latest

  - name: download tomcat server packages
    get_url:
      url: https://apache.ip-connect.vn.ua/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz
      dest: /usr/local

  - name: extract tomcat
    unarchive:
      src: /usr/local/apache-tomcat-8.5.68.tar.gz
      dest: /usr/local
      remote_src: yes
      
  - name: Add users file
    become: true
    copy:
      src: tomcat-users.xml
      dest: /usr/local/apache-tomcat-8.5.68/conf
      
  - name: Add .war package
    become: true
    copy:
      src: War/SampleWebApp.war
      dest: /usr/local/apache-tomcat-8.5.68/webapps

  - name: start tomcat
    become: true
    shell: nohup /usr/local/apache-tomcat-8.5.68/bin/startup.sh &
